function Ontology = importOntology(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   ONTOLOGY = IMPORTFILE(FILENAME) Reads data from text file FILENAME for
%   the default selection.
%
%   ONTOLOGY = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows
%   STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   Ontology = importfile('Ontology.csv', 2, 1840);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2018/08/31 11:22:20

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Format for each line of text:
%   column1: double (%f)
%	column2: text (%q)
%   column3: text (%q)
%	column4: double (%f)
%   column5: text (%q)
%	column6: double (%f)
%   column7: text (%q)
%	column8: text (%q)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%q%q%f%q%f%q%q%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
Ontology = table(dataArray{1:end-1}, 'VariableNames', {'id','acronym','name','parent_structure_id','hemisphere','graph_order','structure_id_path','color_hex_triplet'});

