%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/Aurina/GoogleDrive/Genetics_connectome/HumanExpression/data/genes/rawData/Probes.xlsx
%    Worksheet: Probes.csv
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2018/01/08 15:56:09
function allenProbes = importAllenProbes(filename)
%% Import the data
[~, ~, raw] = xlsread(filename);
raw = raw(2:end,[2,4,6]);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
cellVectors = raw(:,[1,2]);
raw = raw(:,3);

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Create table
allenProbes = table;

%% Allocate imported array to column variable names
allenProbes.probeNames = cellVectors(:,1);
allenProbes.geneName = cellVectors(:,2);
allenProbes.NCBIgeneID = data(:,1);

%% Clear temporary variables
clearvars data raw cellVectors R;
end